### ISSUE TITLE
Missing opensearchpy.OpenSearch.create() method

### ISSUE THREAD

**Issue by sdhoyt** [matthewdeanmartin/openmock#8]
The OpenSearch client's create() method is currently not being mocked. This method creates a new document if one does not exist or returns a 409 error if the document already exists.

I forked the repository and added the method and tests if contributions are being accepted.

**Comment by matthewdeanmartin** [comment]
merged. I'll publish a new release shortly.

**Comment by sdhoyt** [comment]
Thanks!
